services:
  - type: web
    name: lazarus-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: PORT
        value: 8000
